---
apiVersion: v1
kind: Service
metadata:
  name: pzoo
  namespace: spark-test 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
  namespace: spark-test
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
  namespace: spark-test
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: init-config
        env:
        - name: PZOO_REPLICAS
          value: '0'
        - name: REPLICAS
          value: '1'
        - name: ID_OFFSET
          value: '1'
      containers:
      - name: zookeeper
        env:
        - name: REPLICAS
          value: '1'
