namespace: spark-test
bases:
- ../../zookeeper
- ../../kafka
patchesStrategicMerge:
- zoo-9.yaml
- kafka-6.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
  path: kafka-zookeeper-connect-only-zoo.json
